version: '3.8'

services:
  lector-pdf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lector-pdf-v2
    restart: always
    ports:
      - "2024:3001" # Mapear el puerto del contenedor (3001) al puerto del host (2024)
    volumes:
      - ./uploads:/app/uploads # Persistencia de los archivos PDF subidos
    env_file:
      - .env # Usar el archivo .env local para las variables de entorno
