<<<<<<< HEAD
version: '3.8'

services:
  litereader:
    build: .
    ports:
      - "2024:3001"
    environment:
      - PORT=3001
      - NODE_ENV=production
    env_file:
      - .env.local
    restart: unless-stopped
    container_name: litereader-app
=======

version: "3.9"

services:
  frontend:
    build: ./client
    ports:
      - "2024:80"
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "5001:3001"
    env_file:
      - .env
>>>>>>> 68414d2 (version2)
